### ISSUE TITLE
Form Settings and Actions not working?

### ISSUE THREAD

**Issue by minemindmedia** [Log1x/sage-html-forms#7]
Under Settings Tab:
Hiding a form after successful submission not working. Also, form remains filled out.
Redirect to URL after successful submission not working.

Under Actions Tab:
Send email sends a blank body but submissions are saved in HTML Forms.

**Comment by minemindmedia** [comment]
Hi, I've been able to get the email body to work but I am still struggling with getting the form to hide after submitting. It submits fine but the form fields remain filled out and the form doesn't hide either.

Anyone else run into this issue?

**Comment by minemindmedia** [comment]
Still having issues with this. The form doesn't clear/hide after success from a modal window OR the other option to redirect to a thank you page is also not working.

**Comment by hybridvision** [comment]
Hi @minemindmedia,

I came across this problem too and looking at the browser console error, I see that it's because the form fields (ie. the part that you pass across from the component as a slot) are supposed to be wrapped in a `<div>` with the class `hf-fields-wrap`. Once that's there, it works.

I've created a pull request (#14) to correct this problem but in the meantime, you could work around it by wrapping your form content in this tag.

eg.

```html
<x-html-forms :form="$form">

  <div class="hf-fields-wrap">

    <!-- Your original form HTML / Blade markup goes here -->

  </div>

</x-html-forms>
```

Hope that helps!
